spring:
  application:
    name: telephone-manager-backend
  
  datasource:
    url: jdbc:sqlserver://KASAYKO\\SQLEXPRESS:1433;instanceName=SQLEXPRESS;databaseName=PhoneManagementDB;encrypt=true;trustServerCertificate=true;integratedSecurity=false
    username: sa
    password: hamid
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    defer-datasource-initialization: true
  
  security:
    user:
      name: admin
      password: admin123
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-here-make-it-very-long-and-secure
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload:
    path: ./uploads/
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx
    max-size: 10485760 # 10MB

# Logging Configuration
logging:
  level:
    com.telephonemanager: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: TéléphoneManager API
    description: API for managing corporate phone and SIM card assignments
    version: 1.0.0
    contact:
      name: TéléphoneManager Support
      email: support@telephonemanager.com

# Rate Limiting Configuration
rate-limit:
  auth: 5 # requests per minute for authentication
  general: 100 # requests per minute for general API
  upload: 10 # requests per minute for file upload
  export: 5 # requests per hour for export
  system: 10 # requests per minute for system endpoints (admin only) 